name: TestSuites
options:
  deploymentTarget:
    iOS: "12.0"
  bundleIdPrefix: dev.katei
schemes:
  TestSuites:
    build:
      targets:
        TestSuites: [run]
    test:
      targets: [TestSuites]
packages:
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing
    version: 1.8.0
targets:
  Views:
    type: framework
    platform: iOS
    sources: [Sources/Views]
    settings:
      CODE_SIGN_IDENTITY: Apple Development

  TestSuites:
    type: bundle.unit-test
    platform: iOS
    sources: [Sources/TestSuites]
    dependencies:
      - package: SnapshotTesting
      - target: Views
  PrivateUIKit:
    type: framework
    platform: iOS
    sources: [Sources/PrivateUIKit]
    settings:
      MODULEMAP_FILE: $(SRCROOT)/Sources/PrivateUIKit/include/module.modulemap
      CODE_SIGN_IDENTITY: Apple Development
