libxml2.a:
	curl -L https://github.com/kateinoigakukun/libxml2-wasm/releases/download/1.0.0/libxml2-wasm32-unknown-wasi.tar.gz | tar xz
	mv libxml2-wasm32-unknown-wasi/lib/libxml2.a libxml2.a
	rm -rf libxml2-wasm32-unknown-wasi
