name: Run unit tests
on:
  pull_request:
  push:
    branches: [main]
jobs:
  test_on_macOS:
    name: Build and Test on macOS
    strategy:
      matrix:
        xcode-version:
          - /Applications/Xcode_12.2.app
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v2
      - run: sudo xcode-select -s "${{ matrix.xcode-version }}"
      - run: swift --version
      - run: swift test
        env:
          IBCODEGEN_TEST_DESTINATION: "platform=iOS Simulator,name=iPhone 11 Pro"
  coverage:
    name: Collect test coverage
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v2
      - run: swift test --enable-code-coverage
        env:
          IBCODEGEN_TEST_DESTINATION: "platform=iOS Simulator,name=iPhone 11 Pro"
      - run: echo "SWIFT_CODECOV_PATH=$(swift test --show-codecov-path)" >> $GITHUB_ENV
      - uses: codecov/codecov-action@v1
        with:
          file: ${{ env.SWIFT_CODECOV_PATH }}
